//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smtLocations.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class siixsem_smtLocations_dbEntities : DbContext
    {
        public siixsem_smtLocations_dbEntities()
            : base("name=siixsem_smtLocations_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<getSMKTLocations_Result> getSMKTLocations()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSMKTLocations_Result>("getSMKTLocations");
        }
    
        public virtual int clearCurQty()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("clearCurQty");
        }
    
        public virtual int updateItem(string pn, Nullable<int> expired, Nullable<int> qty)
        {
            var pnParameter = pn != null ?
                new ObjectParameter("pn", pn) :
                new ObjectParameter("pn", typeof(string));
    
            var expiredParameter = expired.HasValue ?
                new ObjectParameter("expired", expired) :
                new ObjectParameter("expired", typeof(int));
    
            var qtyParameter = qty.HasValue ?
                new ObjectParameter("qty", qty) :
                new ObjectParameter("qty", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateItem", pnParameter, expiredParameter, qtyParameter);
        }
    
        public virtual int deleteReels()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteReels");
        }
    
        public virtual ObjectResult<getReelsByLoc_Result> getReelsByLoc(string loc)
        {
            var locParameter = loc != null ?
                new ObjectParameter("Loc", loc) :
                new ObjectParameter("Loc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getReelsByLoc_Result>("getReelsByLoc", locParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> insert_reel(string item_id, Nullable<int> init_qty, Nullable<int> curr_qty, Nullable<int> expired, string location)
        {
            var item_idParameter = item_id != null ?
                new ObjectParameter("item_id", item_id) :
                new ObjectParameter("item_id", typeof(string));
    
            var init_qtyParameter = init_qty.HasValue ?
                new ObjectParameter("init_qty", init_qty) :
                new ObjectParameter("init_qty", typeof(int));
    
            var curr_qtyParameter = curr_qty.HasValue ?
                new ObjectParameter("curr_qty", curr_qty) :
                new ObjectParameter("curr_qty", typeof(int));
    
            var expiredParameter = expired.HasValue ?
                new ObjectParameter("expired", expired) :
                new ObjectParameter("expired", typeof(int));
    
            var locationParameter = location != null ?
                new ObjectParameter("location", location) :
                new ObjectParameter("location", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("insert_reel", item_idParameter, init_qtyParameter, curr_qtyParameter, expiredParameter, locationParameter);
        }
    
        public virtual int clearLocations(string @params)
        {
            var paramsParameter = @params != null ?
                new ObjectParameter("params", @params) :
                new ObjectParameter("params", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("clearLocations", paramsParameter);
        }
    
        public virtual ObjectResult<getEvenReels_Result> getEvenReels()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getEvenReels_Result>("getEvenReels");
        }
    
        public virtual ObjectResult<getOddReels_Result> getOddReels()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getOddReels_Result>("getOddReels");
        }
    
        public virtual ObjectResult<getAllReels_Result> getAllReels()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAllReels_Result>("getAllReels");
        }
    }
}
